-- قسم الأقوال والتغريدات.
create table if not exists public.quotes_tweets (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 3 and 500),
  content text not null check (char_length(btrim(content)) between 3 and 100000),
  excerpt text not null default '' check (char_length(excerpt) <= 2000),
  author text not null default 'أ. عبدالملك المخلافي' check (char_length(btrim(author)) between 2 and 200),
  content_type text not null default 'قول' check (content_type in ('قول', 'تغريدة')),
  source_url text check (source_url is null or source_url = '' or source_url ~* '^https?://'),
  published_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quotes_tweets_published_date_idx
  on public.quotes_tweets (published_date desc, id desc);

alter table public.quotes_tweets enable row level security;

drop policy if exists "Public can read quotes and tweets" on public.quotes_tweets;
create policy "Public can read quotes and tweets"
  on public.quotes_tweets for select
  to anon, authenticated
  using (true);

revoke all on table public.quotes_tweets from anon, authenticated;
grant select on table public.quotes_tweets to anon, authenticated;
grant select, insert, update, delete on table public.quotes_tweets to service_role;
grant usage, select on sequence public.quotes_tweets_id_seq to service_role;

-- إدراج القسم الجديد ضمن نظام عدّ المشاهدات الحالي.
alter table public.page_view_totals
  drop constraint if exists page_view_totals_content_type_check;
alter table public.page_view_totals
  add constraint page_view_totals_content_type_check
  check (content_type in ('articles', 'news', 'archive', 'studies', 'testimonials', 'quotes_tweets'));

alter table public.page_view_daily
  drop constraint if exists page_view_daily_content_type_check;
alter table public.page_view_daily
  add constraint page_view_daily_content_type_check
  check (content_type in ('articles', 'news', 'archive', 'studies', 'testimonials', 'quotes_tweets'));

create or replace function public.increment_page_view(
  p_content_type text,
  p_content_id text,
  p_title text,
  p_path text,
  p_local_date date
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_total bigint;
begin
  if p_content_type not in ('articles', 'news', 'archive', 'studies', 'testimonials', 'quotes_tweets')
    or p_content_id is null or char_length(p_content_id) not between 1 and 64
    or p_title is null or char_length(btrim(p_title)) not between 1 and 500
    or p_path is null or char_length(p_path) not between 2 and 300 or left(p_path, 1) <> '/'
    or p_local_date is null
  then
    raise exception 'invalid page-view input' using errcode = '22023';
  end if;

  insert into public.page_view_totals (content_type, content_id, title, path, views)
  values (p_content_type, p_content_id, btrim(p_title), p_path, 1)
  on conflict (content_type, content_id) do update
    set views = public.page_view_totals.views + 1,
        title = excluded.title,
        path = excluded.path,
        updated_at = now()
  returning views into v_total;

  insert into public.page_view_daily (view_date, content_type, content_id, views)
  values (p_local_date, p_content_type, p_content_id, 1)
  on conflict (view_date, content_type, content_id) do update
    set views = public.page_view_daily.views + 1,
        updated_at = now();

  return v_total;
end;
$$;

revoke all on function public.increment_page_view(text, text, text, text, date) from public, anon, authenticated;
grant execute on function public.increment_page_view(text, text, text, text, date) to service_role;
